# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 13:02
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0001_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('welcome_boolean', models.BooleanField(default=False)),
                ('welcome_slide_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_speaker_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_speaker_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_speaker_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_speaker_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('guest_speaker_boolean', models.BooleanField(default=False)),
                ('guest_speaker_slide_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workshop_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('workshop_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('workshop_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('workshop_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('workshop_boolean', models.BooleanField(default=False)),
                ('workshop_slide_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_teams', models.IntegerField(null=True)),
                ('team_project_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('team_project_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('team_project_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('team_project_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('team_project_boolean', models.BooleanField(default=False)),
                ('team_project_slide_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_slideshow_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('team_slideshow_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('team_slideshow_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('team_slideshow_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('team_slideshow_boolean', models.BooleanField(default=False)),
                ('team_slideshow_slide_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('judges_slide_title', models.CharField(blank=True, max_length=255, null=True)),
                ('judges_slide_type', models.CharField(blank=True, max_length=255, null=True)),
                ('judges_slide_file', models.CharField(blank=True, max_length=255, null=True)),
                ('judges_talking_points', ckeditor.fields.RichTextField(blank=True, default=None, max_length=1000, null=True)),
                ('judges_boolean', models.BooleanField(default=False)),
                ('judges_slide_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackathon.Event')),
            ],
        ),

    ]
