# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0002_auto_20161118_0502'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='programflow',
            name='guest_speaker_slide_type',
        ),
        migrations.RemoveField(
            model_name='programflow',
            name='judges_slide_type',
        ),
        migrations.RemoveField(
            model_name='programflow',
            name='team_project_slide_type',
        ),
        migrations.RemoveField(
            model_name='programflow',
            name='team_slideshow_slide_type',
        ),
        migrations.RemoveField(
            model_name='programflow',
            name='welcome_slide_type',
        ),
        migrations.RemoveField(
            model_name='programflow',
            name='workshop_slide_type',
        ),

    ]
